# Generated by Django 3.1.7 on 2021-03-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='t1',
        ),
    ]
